# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1864cbb3340b69cb8f86f8832f7c4d15942b1f950abb003e63bb3ae7b632f97b287804ade477b32c793bbb7a0edcae544b34fd5d899f8444ed044812b219927a

test:
  secret_key_base: 3defd2b52a53c9a89255780b78b012ddb8411dfb946813b5d219137294932802bf4943c2aec4f27aa2b3365ae612ae1f0047c83d0fad83274d5a6b38eb6d1910

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
